from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_STATUS_CHOPPER(object):
    def setupUi(self, STATUS_CHOPPER):
        STATUS_CHOPPER.setObjectName("STATUS_CHOPPER")
        STATUS_CHOPPER.resize(1040, 685)
        STATUS_CHOPPER.setMinimumSize(QtCore.QSize(1040, 685))
        STATUS_CHOPPER.setMaximumSize(QtCore.QSize(1040, 685))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        STATUS_CHOPPER.setFont(font)
        STATUS_CHOPPER.setStyleSheet("bacground:rgb(228, 255, 230);")
        self.formLayoutWidget = QtWidgets.QWidget(STATUS_CHOPPER)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 16, 361, 611))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.description = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.description.setFont(font)
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.description)
        self.l_first = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_first.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_first.setFont(font)
        self.l_first.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_first.setObjectName("l_first")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.l_first)
        self.l_second = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_second.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_second.setFont(font)
        self.l_second.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_second.setObjectName("l_second")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.l_second)
        self.l_three = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_three.setMinimumSize(QtCore.QSize(359, 30))
        self.l_three.setMaximumSize(QtCore.QSize(359, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_three.setFont(font)
        self.l_three.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_three.setObjectName("l_three")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.l_three)
        self.l_four = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_four.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_four.setFont(font)
        self.l_four.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_four.setObjectName("l_four")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.l_four)
        self.l_five = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_five.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_five.setFont(font)
        self.l_five.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_five.setObjectName("l_five")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.l_five)
        self.l_six = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_six.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_six.setFont(font)
        self.l_six.setStyleSheet("border: 2px solid black;\n"
"background: white;")
        self.l_six.setObjectName("l_six")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.l_six)
        self.l_seven = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_seven.setMinimumSize(QtCore.QSize(359, 60))
        self.l_seven.setMaximumSize(QtCore.QSize(359, 75))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_seven.setFont(font)
        self.l_seven.setStyleSheet("border: 2px solid black;\n"
"background: white;")
        self.l_seven.setObjectName("l_seven")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.l_seven)
        self.l_eight = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_eight.setMaximumSize(QtCore.QSize(359, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_eight.setFont(font)
        self.l_eight.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_eight.setObjectName("l_eight")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.l_eight)
        self.l_nine = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_nine.setMaximumSize(QtCore.QSize(359, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_nine.setFont(font)
        self.l_nine.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_nine.setObjectName("l_nine")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.l_nine)
        self.l_ten = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_ten.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_ten.setFont(font)
        self.l_ten.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_ten.setObjectName("l_ten")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.l_ten)
        self.l_eleven = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_eleven.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_eleven.setFont(font)
        self.l_eleven.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_eleven.setObjectName("l_eleven")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.l_eleven)
        self.l_twenty = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_twenty.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_twenty.setFont(font)
        self.l_twenty.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_twenty.setObjectName("l_twenty")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.l_twenty)
        self.l_threteen = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_threteen.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_threteen.setFont(font)
        self.l_threteen.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_threteen.setObjectName("l_threteen")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.l_threteen)
        self.l_fourteen = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_fourteen.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_fourteen.setFont(font)
        self.l_fourteen.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_fourteen.setObjectName("l_fourteen")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.l_fourteen)
        self.l_fifteen = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_fifteen.setMinimumSize(QtCore.QSize(359, 83))
        self.l_fifteen.setMaximumSize(QtCore.QSize(359, 85))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_fifteen.setFont(font)
        self.l_fifteen.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_fifteen.setObjectName("l_fifteen")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.SpanningRole, self.l_fifteen)
        self.l_sixteen = QtWidgets.QLabel(self.formLayoutWidget)
        self.l_sixteen.setMaximumSize(QtCore.QSize(359, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.l_sixteen.setFont(font)
        self.l_sixteen.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.l_sixteen.setObjectName("l_sixteen")
        self.formLayout_2.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.l_sixteen)
        self.label_3 = QtWidgets.QLabel(STATUS_CHOPPER)
        self.label_3.setGeometry(QtCore.QRect(400, 18, 301, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setUnderline(True)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(STATUS_CHOPPER)
        self.label_7.setGeometry(QtCore.QRect(740, 20, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setUnderline(True)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(STATUS_CHOPPER)
        self.label_8.setGeometry(QtCore.QRect(420, 390, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setUnderline(True)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_22 = QtWidgets.QPushButton(STATUS_CHOPPER)
        self.pushButton_22.setGeometry(QtCore.QRect(21, 630, 171, 41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(STATUS_CHOPPER)
        self.pushButton_23.setGeometry(QtCore.QRect(210, 630, 171, 41))
        self.pushButton_23.setObjectName("pushButton_23")
        self.ch_RorW = QtWidgets.QCheckBox(STATUS_CHOPPER)
        self.ch_RorW.setGeometry(QtCore.QRect(690, 50, 70, 17))
        self.ch_RorW.setObjectName("ch_RorW")
        self.pushButton_6 = QtWidgets.QPushButton(STATUS_CHOPPER)
        self.pushButton_6.setGeometry(QtCore.QRect(411, 630, 279, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayoutWidget = QtWidgets.QWidget(STATUS_CHOPPER)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(420, 430, 291, 156))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("border: 2px solid black;\n"
"background: white;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setStyleSheet("border: 2px solid black;\n"
"background: white;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit_4.setMaximumSize(QtCore.QSize(167, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout.addWidget(self.plainTextEdit_4, 4, 1, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit_3.setMaximumSize(QtCore.QSize(167, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout.addWidget(self.plainTextEdit_3, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border: 2px solid black;\n"
"background: white;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.gridLayoutWidget)
        self.plainTextEdit_2.setMaximumSize(QtCore.QSize(167, 28))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout.addWidget(self.plainTextEdit_2, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(STATUS_CHOPPER)
        self.label_15.setGeometry(QtCore.QRect(410, 123, 280, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setUnderline(True)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(STATUS_CHOPPER)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(400, 150, 329, 231))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 4, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_34.setText("")
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 4, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_36.setText("")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 5, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 8, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 2, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 5, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 7, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.label_25.setTextFormat(QtCore.Qt.RichText)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_40.setText("")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 7, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_41.setText("")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 8, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 8, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_38.setText("")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 6, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 6, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_17.setMinimumSize(QtCore.QSize(168, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.label_24.setTextFormat(QtCore.Qt.RichText)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_18.setMinimumSize(QtCore.QSize(168, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.label_16.setTextFormat(QtCore.Qt.RichText)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 7, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 4, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_28.setText("")
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 1, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 3, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_30.setText("")
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 2, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("border: 0.5px solid gray;\n"
"background: white;")
        self.label_32.setText("")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 3, 2, 1, 1)
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(STATUS_CHOPPER)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(750, 42, 281, 621))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(STATUS_CHOPPER)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(420, 50, 257, 54))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.block_combo = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.block_combo.setObjectName("block_combo")
        self.gridLayout_3.addWidget(self.block_combo, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.comList = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.comList.setObjectName("comList")
        self.gridLayout_3.addWidget(self.comList, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(" border: 2px solid black;\n"
"background: white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 1, 2, 1, 1)

        self.retranslateUi(STATUS_CHOPPER)
        QtCore.QMetaObject.connectSlotsByName(STATUS_CHOPPER)

    def retranslateUi(self, STATUS_CHOPPER):
        _translate = QtCore.QCoreApplication.translate
        STATUS_CHOPPER.setWindowTitle(_translate("STATUS_CHOPPER", "CH_MONITOR"))
        self.description.setText(_translate("STATUS_CHOPPER", "Статус прерывателя"))
        self.l_first.setText(_translate("STATUS_CHOPPER", "Тумблер на передней панели"))
        self.l_second.setText(_translate("STATUS_CHOPPER", "Получена команда на останов прерывателя"))
        self.l_three.setText(_translate("STATUS_CHOPPER", "Система сама  прекратила попытки стабилизации\n"
"и сняла напряжение с двигателя"))
        self.l_four.setText(_translate("STATUS_CHOPPER", "Блокировка работы блока С ПЕРЕДНЕЙ ПАНЕЛИ"))
        self.l_five.setText(_translate("STATUS_CHOPPER", "Стабилизация периода"))
        self.l_six.setText(_translate("STATUS_CHOPPER", "Период стабильно в заданном диапазоне"))
        self.l_seven.setText(_translate("STATUS_CHOPPER", "Cелекторных импульсов нет либо они не появились:\n"
"*устанавливается в ISR_T1 при\n"
" превышении количества реперов является;\n"
"*только индикацией совместно с битом 2."))
        self.l_eight.setText(_translate("STATUS_CHOPPER", "Ловушка первого входа в  стабилизацию периода\n"
"селектора Tс"))
        self.l_nine.setText(_translate("STATUS_CHOPPER", "Период селектора Тс в заданном диапазоне\n"
"(контроль точности)"))
        self.l_ten.setText(_translate("STATUS_CHOPPER", "Программа стабилизации фазы"))
        self.l_eleven.setText(_translate("STATUS_CHOPPER", "Фаза   стабильно в заданном диапазоне"))
        self.l_twenty.setText(_translate("STATUS_CHOPPER", "Ловушка первого входа в  стабилизацию фазы  F"))
        self.l_threteen.setText(_translate("STATUS_CHOPPER", "Флаг - F в заданном диапазоне (контроль точности)"))
        self.l_fourteen.setText(_translate("STATUS_CHOPPER", "Период стартов в заданных пределах"))
        self.l_fifteen.setText(_translate("STATUS_CHOPPER", "Зарегистрирована одна из целого комплекса ошибок:\n"
"Выход  фазы из диапазона;\n"
"Выход  из фазы в период;\n"
"При резком изменении фазы;\n"
"!VFL-VFN!>200mkc."))
        self.l_sixteen.setText(_translate("STATUS_CHOPPER", "Неверное задание"))
        self.label_3.setText(_translate("STATUS_CHOPPER", "Информация о текущем блоке"))
        self.label_7.setText(_translate("STATUS_CHOPPER", "Седения о работе"))
        self.label_8.setText(_translate("STATUS_CHOPPER", "Редактировать параметры"))
        self.pushButton_22.setText(_translate("STATUS_CHOPPER", "Стоп"))
        self.pushButton_23.setText(_translate("STATUS_CHOPPER", "Старт"))
        self.ch_RorW.setText(_translate("STATUS_CHOPPER", "W"))
        self.pushButton_6.setText(_translate("STATUS_CHOPPER", "ОТПРАВИТЬ"))
        self.label_13.setText(_translate("STATUS_CHOPPER", "Данные"))
        self.label_6.setText(_translate("STATUS_CHOPPER", "Ответ"))
        self.label_12.setText(_translate("STATUS_CHOPPER", "Регистр (0 - 400)"))
        self.label_15.setText(_translate("STATUS_CHOPPER", "Онлайн параметры"))
        self.label_19.setText(_translate("STATUS_CHOPPER", "период селекторных импульсов"))
        self.label_33.setText(_translate("STATUS_CHOPPER", "4"))
        self.label_26.setText(_translate("STATUS_CHOPPER", "пропущенные старты"))
        self.label_29.setText(_translate("STATUS_CHOPPER", "2"))
        self.label_35.setText(_translate("STATUS_CHOPPER", "344"))
        self.label_39.setText(_translate("STATUS_CHOPPER", "236"))
        self.label_25.setText(_translate("STATUS_CHOPPER", "значение"))
        self.label_42.setText(_translate("STATUS_CHOPPER", "345"))
        self.label_37.setText(_translate("STATUS_CHOPPER", "234"))
        self.label_17.setText(_translate("STATUS_CHOPPER", "текущее рассогласование F\n"
" c разрешением [359]"))
        self.label_24.setText(_translate("STATUS_CHOPPER", "регистр"))
        self.label_18.setText(_translate("STATUS_CHOPPER", "текущее рассогласование Ts\n"
" c разрешением [359]"))
        self.label_21.setText(_translate("STATUS_CHOPPER", "режим ОКНО  "))
        self.label_16.setText(_translate("STATUS_CHOPPER", "имя"))
        self.label_27.setText(_translate("STATUS_CHOPPER", "1"))
        self.label_23.setText(_translate("STATUS_CHOPPER", "пересчет реактора    "))
        self.label_20.setText(_translate("STATUS_CHOPPER", "период стартов"))
        self.label_22.setText(_translate("STATUS_CHOPPER", "пересчет селектора"))
        self.label_31.setText(_translate("STATUS_CHOPPER", "3"))
        self.label_4.setText(_translate("STATUS_CHOPPER", "      СOM        "))
        self.label.setText(_translate("STATUS_CHOPPER", "Номер Блока"))
        self.pushButton.setText(_translate("STATUS_CHOPPER", "Подключиться"))
        self.pushButton_2.setText(_translate("STATUS_CHOPPER", "Отключиться"))
